import React, { useEffect } from 'react';
import PublicLayout from './components/PublicLayout';

export default function PrivacyPage() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <PublicLayout>
            <div className="bg-white rounded-[2.5rem] shadow-xl border border-slate-100 p-8 md:p-16 w-full max-w-4xl flex flex-col mx-auto">
                <div className="mb-10 pb-8 border-b border-slate-100">
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-orange-50 border border-orange-100 shadow-sm mb-6">
                        <span className="flex h-2 w-2 rounded-full bg-orange-500"></span>
                        <span className="text-xs font-bold text-orange-700 uppercase tracking-wider">Legal</span>
                    </div>
                    <h1 className="text-3xl md:text-5xl font-black mb-4 tracking-tight text-slate-900">Privacy Policy</h1>
                    <p className="text-slate-500 font-medium">Last Updated: March 6, 2026</p>
                </div>

                <div className="prose max-w-none space-y-8 text-[15px] leading-relaxed text-slate-600">
                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">1. Introduction</h2>
                        <p><strong>Otter</strong> ("we," "our," or "us") is committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, store, and share your personal information when you use our AI-powered screenshot vault service at <strong>otter-app.com</strong> (the "Service").</p>
                        <p>By using Otter, you consent to the data practices described in this policy. If you do not agree with any part of this policy, please discontinue use of our Service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">2. Information We Collect</h2>
                        <p>We collect the following categories of information:</p>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">2.1 Account Information</h3>
                        <ul className="list-disc pl-6 space-y-1.5 marker:text-orange-500">
                            <li><strong>Email address</strong> — collected via Google OAuth during sign-in.</li>
                            <li><strong>Display name and profile picture</strong> — provided by your Google account.</li>
                            <li><strong>User ID</strong> — a unique identifier generated by our authentication system.</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">2.2 Uploaded Content</h3>
                        <ul className="list-disc pl-6 space-y-1.5 marker:text-orange-500">
                            <li><strong>Images and screenshots</strong> — files you upload to your vault.</li>
                            <li><strong>AI-generated metadata</strong> — categories, tags, summaries, detected amounts, dates, and OTP codes extracted by our AI analysis.</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">2.3 Usage &amp; Device Data</h3>
                        <ul className="list-disc pl-6 space-y-1.5 marker:text-orange-500">
                            <li>Browser type, operating system, and device information.</li>
                            <li>IP address and approximate geographic location.</li>
                            <li>Pages visited, features used, and interaction timestamps.</li>
                            <li>Referring URLs and session duration.</li>
                        </ul>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">2.4 Cookies &amp; Tracking Technologies</h3>
                        <p>We use cookies, web beacons, and similar technologies to enhance your experience, analyze usage, and deliver relevant advertisements. See Section 6 for full details on third-party advertising cookies.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">3. How We Use Your Information</h2>
                        <p>We use the collected information for the following purposes:</p>
                        <ul className="list-disc pl-6 space-y-1.5 mt-2 marker:text-orange-500">
                            <li><strong>Service Delivery:</strong> To host, store, organize, and display your uploaded images and their AI-generated metadata.</li>
                            <li><strong>AI Processing:</strong> To apply Optical Character Recognition (OCR), automated tagging, categorization, and data extraction to your images for the sole purpose of organizing your vault.</li>
                            <li><strong>Account Management:</strong> To authenticate your identity and manage your subscription and preferences.</li>
                            <li><strong>Service Improvement:</strong> To understand usage patterns and improve features, performance, and reliability.</li>
                            <li><strong>Communications:</strong> To send important service updates, security alerts, and, with your consent, promotional content.</li>
                            <li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, and legal processes.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">4. AI Processing Disclosure</h2>
                        <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 mt-2">
                            <p className="text-blue-800 font-medium"><strong>Important:</strong> Your uploaded images are processed by AI and OCR technologies for the sole purpose of organizing, categorizing, and extracting useful data within your personal vault. Your images are <strong>NOT</strong> sold, shared, or transferred to any third party for their own purposes. AI processing is performed exclusively to deliver the Otter service to you.</p>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">5. Data Sharing &amp; Disclosure</h2>
                        <p>We do <strong>not</strong> sell your personal data or uploaded images to third parties. We may share information only in the following circumstances:</p>
                        <ul className="list-disc pl-6 space-y-1.5 mt-2 marker:text-orange-500">
                            <li><strong>Service Providers:</strong> We use trusted third-party services (e.g., Supabase for hosting/database, AI model providers for analysis) that process data on our behalf under strict data processing agreements.</li>
                            <li><strong>Legal Requirements:</strong> When required by law, regulation, or legal process, or to protect the rights, safety, or property of Otter, our users, or the public.</li>
                            <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, your data may be transferred as part of the transaction.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">6. Third-Party Advertising (Google AdSense)</h2>
                        <div className="bg-orange-50 border border-orange-200 rounded-2xl p-6 mt-2 mb-4">
                            <p className="text-orange-800 font-medium mb-3">We use third-party vendors, including Google, which use cookies to serve ads based on a user's prior visits to your website or other websites. Google's use of advertising cookies enables it and its partners to serve ads to our users based on their visit to Otter and/or other sites on the Internet.</p>
                        </div>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">6.1 DoubleClick DART Cookie</h3>
                        <p>Google, as a third-party vendor, uses the DoubleClick DART cookie to serve interest-based advertisements to you when you visit Otter or other websites across the Internet. This cookie is used by Google to display ads that are relevant to you based on your browsing history and interests.</p>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">6.2 Opting Out</h3>
                        <p>You may opt out of the use of the DART cookie by visiting the <a href="https://adssettings.google.com/authenticated" target="_blank" rel="noopener noreferrer" className="text-orange-600 hover:text-orange-500 font-bold transition-colors">Google Ads Settings page</a>. Additionally, you can opt out of personalized advertising by visiting <a href="https://www.aboutads.info/choices/" target="_blank" rel="noopener noreferrer" className="text-orange-600 hover:text-orange-500 font-bold transition-colors">www.aboutads.info/choices</a>.</p>

                        <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-900">6.3 Managing Cookies</h3>
                        <p>You can control and manage cookies through your browser settings. Most browsers allow you to refuse cookies, delete existing cookies, or alert you before a cookie is placed. Note that disabling cookies may affect the functionality of certain features of the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">7. Data Security</h2>
                        <p>We take the security of your "vault" seriously and implement the following measures:</p>
                        <ul className="list-disc pl-6 space-y-1.5 mt-2 marker:text-orange-500">
                            <li><strong>Secure Cloud Storage:</strong> All uploaded images are stored in encrypted cloud storage infrastructure provided by Supabase.</li>
                            <li><strong>Encryption in Transit:</strong> All data transmitted between your browser and our servers is encrypted using TLS/SSL protocols.</li>
                            <li><strong>Authentication Security:</strong> We use industry-standard OAuth 2.0 via Google for secure sign-in, ensuring we never store your Google password.</li>
                            <li><strong>Row-Level Security:</strong> Database access controls ensure that your data can only be accessed by your authenticated account.</li>
                            <li><strong>Regular Monitoring:</strong> We monitor our systems for potential vulnerabilities and breaches.</li>
                        </ul>
                        <p className="mt-3">While we implement commercially reasonable security measures, no method of transmission or storage is 100% secure. We cannot guarantee absolute security of your data.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">8. Your Rights (GDPR &amp; CCPA)</h2>
                        <p>Depending on your location, you may have the following rights regarding your personal data:</p>

                        <div className="grid md:grid-cols-2 gap-4 mt-6">
                            <div className="rounded-2xl p-5 border bg-slate-50 border-slate-100">
                                <h4 className="font-bold text-sm mb-2 text-slate-900">📋 Right to Access</h4>
                                <p className="text-sm">You have the right to request a copy of the personal data we hold about you.</p>
                            </div>
                            <div className="rounded-2xl p-5 border bg-slate-50 border-slate-100">
                                <h4 className="font-bold text-sm mb-2 text-slate-900">✏️ Right to Rectification</h4>
                                <p className="text-sm">You have the right to request correction of any inaccurate or incomplete personal data.</p>
                            </div>
                            <div className="rounded-2xl p-5 border bg-slate-50 border-slate-100">
                                <h4 className="font-bold text-sm mb-2 text-slate-900">🗑️ Right to Erasure</h4>
                                <p className="text-sm">You have the right to request deletion of your personal data entirely from our system.</p>
                            </div>
                            <div className="rounded-2xl p-5 border bg-slate-50 border-slate-100">
                                <h4 className="font-bold text-sm mb-2 text-slate-900">📦 Right to Data Portability</h4>
                                <p className="text-sm">You have the right to receive your data. Our "Download All" feature allows you to export your entire vault as a ZIP file.</p>
                            </div>
                        </div>

                        <p className="mt-6">To exercise any of these rights, please contact us at <a href="mailto:privacy@otter-app.com" className="text-orange-600 hover:text-orange-500 font-bold transition-colors">privacy@otter-app.com</a>. We will respond to verified requests within 30 days.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">9. Data Retention</h2>
                        <p>We retain your personal data and uploaded content for as long as your account is active or as needed to provide the Service. If you delete your account, we will delete your data within 30 days, except where retention is required by law or for legitimate business purposes.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">10. Children's Privacy</h2>
                        <p>Otter is not intended for use by individuals under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected data from a child under 13, we will take steps to delete such information promptly.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">11. International Data Transfers</h2>
                        <p>Your data may be processed and stored on servers located outside your country of residence, including in the United States and the European Union. By using Otter, you consent to the transfer of your data to these locations, where data protection laws may differ from those in your jurisdiction.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">12. Changes to This Privacy Policy</h2>
                        <p>We may update this Privacy Policy from time to time. When we do, we will revise the "Last Updated" date at the top and, for material changes, notify you via email or a prominent notice within the Service. We encourage you to review this policy periodically.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mb-3 text-slate-900">13. Contact Us</h2>
                        <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us at:</p>
                        <div className="mt-3 rounded-xl p-5 border bg-orange-50/50 border-orange-100">
                            <p className="font-bold text-slate-900">Otter Privacy Team</p>
                            <p>Email: <a href="mailto:privacy@otter-app.com" className="text-orange-600 hover:text-orange-500 font-bold transition-colors">privacy@otter-app.com</a></p>
                        </div>
                    </section>
                </div>
            </div>
        </PublicLayout>
    );
}
